apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name}}
spec:
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      name: "{{ .Chart.Name }}"
    spec:
      restartPolicy: "OnFailure"
      containers:
        - name: "{{ .Chart.Name }}"
          {{- if eq .Values.image.tag "latest"}}
          image: "{{ .Values.image.name}}/{{ .Chart.Name }}:{{ .Chart.AppVersion }}"
          {{- else}}
          image: "{{ .Values.image.devRepo }}/{{ .Chart.Name }}:{{ .Values.image.tag }}"
          {{- end}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GCS_OUTPUT_BUCKET
              value: "{{ .Values.output.bucket }}"
            - name: OUTPUT_DIRECTORY
              value: "{{ .Values.output.directory }}"
            - name: OUTPUT_FILENAME_PREFIX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
