image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: eu.gcr.io/ons-rasrmbs-management
  tag: latest
  pullPolicy: Always

output:
  bucket: "ras-rm-performance-20220908-results"
  directory: "."
